services:
  fe:
    image: worameta/wonglao-frontend:latest
    ports:
      - "80:80"
  be:
    image: worameta/wonglao-backend:latest
    ports:
      - "8000:8000"
    environment:
      CORS: ${CORS}
      API_KEY: ${API_KEY}      
  pg:
  rd: